In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
data=[1,2,90,3,4]
ser=pd.Series(data)
print(ser)

0     1
1     2
2    90
3     3
4     4
dtype: int64

In [ ]:
d={"g":1,"f":2,"e":3,"f":2,"p":5}
ser=pd.Series(d)
print(ser)

g    1
f    2
e    3
p    5
dtype: int64

In [ ]:
data=[3,4,5,6]
s=pd.Series(data)
print(s)
a=pd.Series(data,index=["a","b","c","d"])
print(a)

0    3
1    4
2    5
3    6
dtype: int64
a    3
b    4
c    5
d    6
dtype: int64

In [ ]:
#updating the series
d=[1,2,3,4,5,6]
s=pd.Series(d)
print(s)
s[5]=90
s[6]=45
print(s)
s=s.drop(1)
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
0     1
1     2
2     3
3     4
4     5
5    90
6    45
dtype: int64
0     1
2     3
3     4
4     5
5    90
6    45
dtype: int64

In [ ]:
#inserting range of values
data=[8,7,6,45,2]
s=pd.Series(data, index=[0,1,2,3,4])
new_data=pd.Series([100,200,300],index=[5,6,7])
s=pd.concat([s,new_data])
print(s)

0      8
1      7
2      6
3     45
4      2
5    100
6    200
7    300
dtype: int64

In [ ]:
#drop of two index values
datadata=[8,7,6,45,2]
s=pd.Series(data, index=[0,1,2,3,4])
new_data=pd.Series([100,200,300],index=[5,6,7])
s=pd.concat([s,new_data])
s=s.drop(1)
print(s)

0      8
2      6
3     45
4      2
5    100
6    200
7    300
dtype: int64

In [ ]:
#remove range
datadata=[8,7,6,45,2]
s=pd.Series(data, index=[0,1,2,3,4])
s=s.drop(s.index[0:3])
print(s)

0     8
1     7
2     6
3    45
4     2
dtype: int64

In [ ]:
#del values
datadata=[8,7,6,45,2]
s=pd.Series(data, index=[0,1,2,3,4])
print(s)
del(s)

0     8
1     7
2     6
3    45
4     2
dtype: int64

In [ ]:
# pandas Series
import pandas as pd
stdID=[101,102,103,104,105]
marks=[78,85,92,67,88]
s=pd.Series(marks,index=stdID)
print(s)

101    78
102    85
103    92
104    67
105    88
dtype: int64

In [ ]:
print(s[103])

92

In [ ]:
import pandas as pd
empID=[1001,1002,1003,1004,1005]
sal=[35000,42000,38000,50000,45000]
s=pd.Series(sal,index=empID)
print(s)

1001    35000
1002    42000
1003    38000
1004    50000
1005    45000
dtype: int64

In [ ]:
s[1003]=40000
print(s)

1003    40000
dtype: int64

In [ ]:
import pandas as pd
productID=[101,102,103,104,105]
price=[500,750,1200,900,1500]
s=pd.Series(price,index=productID)
print(s)

101     500
102     750
103    1200
104     900
105    1500
dtype: int64

In [ ]:
print(s[103])

1200

In [ ]:
s[102]=800
print(s)

101     500
102     800
103    1200
104     900
105    1500
dtype: int64

In [ ]:
import pandas as pd
balance=pd.series(25000,45000,32000,18000,60000)

In [ ]:
import pandas as pd
Days=["Monday","Tuesday","Wednesday","Thursday","Friday"]
Salary=[5000,7000,6000,9000,8000]
s=pd.Series(Salary,index=Days)
print(s)
print(s.head(2))
print(s.tail(3))
print(s.index)
print(len(s))
print(s.values)
print(s.shape)
print(s["Monday"])
print(s[["Monday","Wednesday"]])
print(s.iloc[0])
print(s.iloc[2])

Monday       5000
Tuesday      7000
Wednesday    6000
Thursday     9000
Friday       8000
dtype: int64
Monday     5000
Tuesday    7000
dtype: int64
Wednesday    6000
Thursday     9000
Friday       8000
dtype: int64
Index(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], dtype='object')
5
[5000 7000 6000 9000 8000]
(5,)
5000
Monday       5000
Wednesday    6000
dtype: int64
5000
6000

In [ ]:
print(s.iloc[0:4])

Monday       5000
Tuesday      7000
Wednesday    6000
Thursday     9000
dtype: int64

In [ ]:
#filtering using a condition and grater than 6000
print(s>6000)
print(s<6000)
print(s[s>6000])

Monday       False
Tuesday       True
Wednesday    False
Thursday      True
Friday        True
dtype: bool
Monday        True
Tuesday      False
Wednesday    False
Thursday     False
Friday       False
dtype: bool
Tuesday     7000
Thursday    9000
Friday      8000
dtype: int64

In [ ]:
#is null and isna() finding msising values and find the missing values and droping the values
import pandas as pd
Days=[7000,8000,None,5000,None]
s=pd.Series(Days)
print(s)
print(s.isna())
print(s.isna().sum())
print(s.dropna())

0    7000.0
1    8000.0
2       NaN
3    5000.0
4       NaN
dtype: float64
0    False
1    False
2     True
3    False
4     True
dtype: bool
2
0    7000.0
1    8000.0
3    5000.0
dtype: float64

In [ ]:
#fill na which will replace the value with 0 and also filling the avreage mean
print(s.fillna(0))
print(s.fillna(s.mean()))

0    7000.0
1    8000.0
2       0.0
3    5000.0
4       0.0
dtype: float64
0    7000.000000
1    8000.000000
2    6666.666667
3    5000.000000
4    6666.666667
dtype: float64

In [ ]:
#create a series of a whether report in 2025 12 months jan 20,feb 25,March None,April 30, May 40,June None,July None,August 36,Sep 22, Oct 20,Nov none,december 10
import pandas as pd
Days=[20,25,None,30,40,None,None,36,22,20,None,10]
Months=["jan","feb","march","apr","may","june","july","august","sep","oct","nov","dec"]
s=pd.Series(Days,index=Months)
print(s)
print(s[["jan","apr"]])

jan       20.0
feb       25.0
march      NaN
apr       30.0
may       40.0
june       NaN
july       NaN
august    36.0
sep       22.0
oct       20.0
nov        NaN
dec       10.0
dtype: float64
jan    20.0
apr    30.0
dtype: float64
nan

In [ ]:
#selecting, filtering and viewing
print(s.iloc[2])
print(s.iloc[3])
print(s>35)
print(s<30)
print(s.isna())
print(s.isna().sum())

nan
30.0
jan       False
feb       False
march     False
apr       False
may        True
june      False
july      False
august     True
sep       False
oct       False
nov       False
dec       False
dtype: bool
jan        True
feb        True
march     False
apr       False
may       False
june      False
july      False
august    False
sep        True
oct        True
nov       False
dec        True
dtype: bool
jan       False
feb       False
march      True
apr       False
may       False
june       True
july       True
august    False
sep       False
oct       False
nov        True
dec       False
dtype: bool
4

In [ ]:
#aggregates
print(s.sum())
print(s.mean())
print(s.min())
print(s.max())
print(s.count())
print(s.std())

203.0
25.375
10.0
40.0
8
9.664921845815117

In [ ]:
#merging\ joining
s1=pd.Series([100,200,300,500])
s2=pd.Series([10,20,30,40])
result=pd.concat([s1,s2])
print(result)

0    100
1    200
2    300
3    500
0     10
1     20
2     30
3     40
dtype: int64

In [ ]:
#Data frames and its creations
import pandas as pd
data=[
  ["Hanifa",25,35000],
  ["Areefa",22,30000],
  ["Sarayu",23,40000]
]
df=pd.DataFrame(data)
print(df)

        0   1      2
0  Hanifa  25  35000
1  Areefa  22  30000
2  Sarayu  23  40000

In [ ]:
#Data Frames using tuples
import pandas as pd
data=(
  ("Hanifa",25,35000),
  ("Areefa",22,30000),
  ("Sarayu",23,40000)
)
df=pd.DataFrame(data)
print(df)

        0   1      2
0  Hanifa  25  35000
1  Areefa  22  30000
2  Sarayu  23  40000

In [ ]:
#Data Frames using set
import pandas as pd
data=[
  ["Hanifa",25,35000],
  ["Areefa",22,30000],
  ["Sarayu",23,40000]
]
df=pd.DataFrame(
  data,
  columns=["Name","Age","Salary"]
)
print(df)

     Name  Age  Salary
0  Hanifa   25   35000
1  Areefa   22   30000
2  Sarayu   23   40000

In [ ]:
# using set
import pandas as pd
s={1,2,3,4,4,5,6,7,8}
d=pd.DataFrame(list(s))
print(d)

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8

In [ ]:
#using dataframe with dictonaries
import pandas as pd
data={
    "Name":["Ravi","Priya","Hanifa","Sarayu","Thiskani"],
    "Age":[22,25,26,27,28],
    "City":["Hyderbad","Chennai","Banglore","Vizag","Mumbai"]
}
df=pd.DataFrame(data)
print(df)

       Name  Age      City
0      Ravi   22  Hyderbad
1     Priya   25   Chennai
2    Hanifa   26  Banglore
3    Sarayu   27     Vizag
4  Thiskani   28    Mumbai
       Name  Age      City
0      Ravi   22  Hyderbad
1     Priya   25   Chennai
2    Hanifa   26  Banglore
3    Sarayu   27     Vizag
4  Thiskani   28    Mumbai

In [ ]:
#viewing data in dataframe
print(df.head())
print(df.tail())
print(len(df))
print(df.shape[0])
print(df.shape[1])
print(df.info())
print(df.describe())

       Name  Age      City
0      Ravi   22  Hyderbad
1     Priya   25   Chennai
2    Hanifa   26  Banglore
3    Sarayu   27     Vizag
4  Thiskani   28    Mumbai
       Name  Age      City
0      Ravi   22  Hyderbad
1     Priya   25   Chennai
2    Hanifa   26  Banglore
3    Sarayu   27     Vizag
4  Thiskani   28    Mumbai
5
5
3
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
None
             Age
count   5.000000
mean   25.600000
std     2.302173
min    22.000000
25%    25.000000
50%    26.000000
75%    27.000000
max    28.000000

In [ ]:
print(df["s1"])
print(df[['s1','s2']])
print(df.iloc[0,1])
print(df.iloc[2])
print(df.iloc[0:4])

0        Ravi
1       Priya
2      Hanifa
3      Sarayu
4    Thiskani
Name: s1, dtype: object
         s1  s2
0      Ravi  22
1     Priya  25
2    Hanifa  26
3    Sarayu  27
4  Thiskani  28
22
s1      Hanifa
s2          26
s3    Banglore
Name: 2, dtype: object
       s1  s2        s3
0    Ravi  22  Hyderbad
1   Priya  25   Chennai
2  Hanifa  26  Banglore
3  Sarayu  27     Vizag

In [ ]:
print(df.iloc[0,1])
print(df.iloc[1,2])
print(df.iloc[0:4])

22
Chennai
s1      Hanifa
s2          26
s3    Banglore
Name: 2, dtype: object
       s1  s2        s3
0    Ravi  22  Hyderbad
1   Priya  25   Chennai
2  Hanifa  26  Banglore
3  Sarayu  27     Vizag

In [ ]:
print(df.iloc[2])

s1      Hanifa
s2          26
s3    Banglore
Name: 2, dtype: object

In [ ]:
s1=[7,8,6,3]
s2=[4,5,1,7]
s3=[5,6,9,2,4,7]
s=pd.Series(s1)
b=pd.Series(s2)
c=pd.Series(s3)
data={"Name":s,"Age":b,"Salary":c}
d=pd.DataFrame(data)
print(d)

   Name  Age  Salary
0   7.0  4.0       5
1   8.0  5.0       6
2   6.0  1.0       9
3   3.0  7.0       2
4   NaN  NaN       4
5   NaN  NaN       7

In [ ]:
#rename of the columns for single and multiple
df.columns=["num1","num2","num3"]
print(df)

       num1  num2      num3
0      Ravi    22  Hyderbad
1     Priya    25   Chennai
2    Hanifa    26  Banglore
3    Sarayu    27     Vizag
4  Thiskani    28    Mumbai
       num1  num2      num3
0      Ravi    22  Hyderbad
1     Priya    25   Chennai
2    Hanifa    26  Banglore
3    Sarayu    27     Vizag
4  Thiskani    28    Mumbai

In [ ]:
#rename for multiple columns
df.rename(
    columns={
        'num1':'s1',
        'num2':'s2',
        'num3':'s3'

    },
    inplace=True
)
print(df)

         s1  s2        s3
0      Ravi  22  Hyderbad
1     Priya  25   Chennai
2    Hanifa  26  Banglore
3    Sarayu  27     Vizag
4  Thiskani  28    Mumbai

In [ ]:
age=df[df['s2']>23]
print(age)

         s1  s2        s3
1     Priya  25   Chennai
2    Hanifa  26  Banglore
3    Sarayu  27     Vizag
4  Thiskani  28    Mumbai

In [ ]:
#multiple condition using & and |
result=df[
    (df['s2']>23) &
    (df['s3']=='Vizag')
]
print(result)

       s1  s2     s3
3  Sarayu  27  Vizag

In [ ]:
#claening data in dataframes
print(df.isnull())
print(df.isna())
print(df.isna().sum())
print(df.fillna(0))

      s1     s2     s3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
      s1     s2     s3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
s1    0
s2    0
s3    0
dtype: int64
         s1  s2        s3
0      Ravi  22  Hyderbad
1     Priya  25   Chennai
2    Hanifa  26  Banglore
3    Sarayu  27     Vizag
4  Thiskani  28    Mumbai

In [ ]:
import pandas as pd
data={
    "Name":["Ravi","Priya","Hanifa","Sarayu","Thiskani"],
    "Age":[22,25,26,27,28],
    "City":["Hyderbad","Chennai","Banglore","Vizag","Mumbai"],
    "Salary":[35000,45000,50000,55000,53000]
}
df=pd.DataFrame(data)
print(df)

TypeError: 'DataFrame' object is not callable

In [ ]:
print(df["Name"])

0        Ravi
1       Priya
2      Hanifa
3      Sarayu
4    Thiskani
Name: Name, dtype: object

In [ ]:
print(df[["Name","Salary"]])

       Name  Salary
0      Ravi   35000
1     Priya   45000
2    Hanifa   50000
3    Sarayu   55000
4  Thiskani   53000

In [ ]:
age=df[df['Age']>23]
print(age)

       Name  Age      City  Salary
1     Priya   25   Chennai   45000
2    Hanifa   26  Banglore   50000
3    Sarayu   27     Vizag   55000
4  Thiskani   28    Mumbai   53000

In [ ]:
print[df["Salary"]>50000]

/tmp/ipykernel_1034/1902771542.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print[df["Salary"]>50000]

       Name  Age    City  Salary
3    Sarayu   27   Vizag   55000
4  Thiskani   28  Mumbai   53000

In [ ]:
print[df["City"]=='Chennai']

/tmp/ipykernel_1034/3528376112.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print[df["City"]=='Chennai']

    Name  Age     City  Salary
1  Priya   25  Chennai   45000

In [ ]:
#Finding duplicates
import pandas as pd
data = {
    "EmpID":[101,102,103,104,105,106,107,108,109,110,110],
    "Name":["Ravi","PRIYA","Arun","sneha","Kiran","ANJALI","Vikram","meena","RAHUL","Sneha","Sneha"],
    "City":["Hyderbad","Hyderbad","Chennai","Chennai","Banglore","BANGLORE","Mumbai","MUMBAI","Delhi","Hyderbad","Hyderbad"],
    "Salary":[30000,40000,3500,4500,32000,50000,38000,42000,36000,45000,45000]
}
df = pd.DataFrame(data)
print(df)

city_codes = {
    "Hyd":"Hyderbad",
    "Che":"Chennai",
    "Del":"Delhi"
}

    EmpID    Name      City  Salary
0     101    Ravi  Hyderbad   30000
1     102   PRIYA  Hyderbad   40000
2     103    Arun   Chennai    3500
3     104   sneha   Chennai    4500
4     105   Kiran  Banglore   32000
5     106  ANJALI  BANGLORE   50000
6     107  Vikram    Mumbai   38000
7     108   meena    MUMBAI   42000
8     109   RAHUL     Delhi   36000
9     110   Sneha  Hyderbad   45000
10    110   Sneha  Hyderbad   45000

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [ ]:
#printing duplicates rows
print(df[df.duplicated()])

    EmpID   Name      City  Salary
10    110  Sneha  Hyderbad   45000

In [ ]:
count = df.duplicated().sum()
print(count)

1

In [ ]:
# finding all rows involved in duplicates
df.duplicated()
df[df.duplicated(keep=False)]

    EmpID   Name      City  Salary
9     110  Sneha  Hyderbad   45000
10    110  Sneha  Hyderbad   45000

In [ ]:
duplicate=df[df.duplicated(keep=False)]
print(duplicate)

    EmpID   Name      City  Salary
9     110  Sneha  Hyderbad   45000
10    110  Sneha  Hyderbad   45000

In [ ]:
df["Salary"].sum()

np.int64(366000)

In [ ]:
# only duplicate
dup_row=df[df.duplicated()]
total=dup_row["Salary"].sum()
print(total)

45000

In [ ]:
# original and dupliacte sums
dup_row=df[df.duplicated(keep=False)]
total=dup_row["Salary"].sum()
print(total)

90000

In [ ]:
# finding the duplicates specific column
#df["EmpID"].duplicated()
df[df["EmpID"].duplicated()]

    EmpID   Name      City  Salary
10    110  Sneha  Hyderbad   45000

In [ ]:
#display the rows having duplicate employee ids
#find the duplicate names
df[df["Name"].duplicated(keep=False)]

    EmpID   Name      City  Salary
9     110  Sneha  Hyderbad   45000
10    110  Sneha  Hyderbad   45000

In [ ]:
# to drop the duplicates rows
df.drop_duplicates
print(df)

AttributeError: 'NoneType' object has no attribute 'drop_duplicates'

In [ ]:
# to drop the names permanently
d =df.drop_duplicates(inplace=True)
print(df)

AttributeError: 'NoneType' object has no attribute 'drop_duplicates'

In [ ]:
# keep first occurance and last occurance
df.drop_duplicates(keep="first")
df.drop_duplicates(keep="last")

    EmpID    Name      City  Salary
0     101    Ravi  Hyderbad   30000
1     102   PRIYA  Hyderbad   40000
2     103    Arun   Chennai    3500
3     104   sneha   Chennai    4500
4     105   Kiran  Banglore   32000
5     106  ANJALI  BANGLORE   50000
6     107  Vikram    Mumbai   38000
7     108   meena    MUMBAI   42000
8     109   RAHUL     Delhi   36000
10    110   Sneha  Hyderbad   45000

In [ ]:
# if we want to delete all the duplicates occurances
df.drop_duplicates(keep=False)

   EmpID    Name      City  Salary
0    101    Ravi  Hyderbad   30000
1    102   PRIYA  Hyderbad   40000
2    103    Arun   Chennai    3500
3    104   sneha   Chennai    4500
4    105   Kiran  Banglore   32000
5    106  ANJALI  BANGLORE   50000
6    107  Vikram    Mumbai   38000
7    108   meena    MUMBAI   42000
8    109   RAHUL     Delhi   36000

In [ ]:
# delete entire rows based on specific column
df = df.drop_duplicates(
    subset=["EmpID"],
    keep="first")
print(df)

   EmpID    Name      City  Salary
0    101    Ravi  Hyderbad   30000
1    102   PRIYA  Hyderbad   40000
2    103    Arun   Chennai    3500
3    104   sneha   Chennai    4500
4    105   Kiran  Banglore   32000
5    106  ANJALI  BANGLORE   50000
6    107  Vikram    Mumbai   38000
7    108   meena    MUMBAI   42000
8    109   RAHUL     Delhi   36000
9    110   Sneha  Hyderbad   45000

In [ ]:
import pandas as pd
data = {
   "TransactionID": [1001, 1002, 1003, 1004, 1005,1006, 1007, 1008, 1009, 1010, 1010, 1011],
   "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran", "Anjali", "Vikram", "Meena", "Rahul", "Sneha", "Sneha", "Kiran"],
   "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse", "Keyboard", "Monitor", "Laptop", "Mobile", "Headphones","Headphones", "Mouse"],
   "Amount": [55000, 25000, 30000, 5000, 1500,2500, 18000, 55000, 22000, 5000,5000, 1500]}
df = pd.DataFrame(data)
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [ ]:
# find total number of duplicates rows
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
dtype: bool

In [ ]:
# original transaction and its dulpicates and all records involved in complete dupliction
dup_row=df[df.duplicated(keep=False)]
print(dup_row)

    TransactionID Customer     Product  Amount
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000

In [ ]:
# calculate total amount associated with the duplicate transcation records
dup_row=df[df.duplicated(keep=False)]
total=dup_row["Amount"].sum()
print(total)

10000

In [ ]:
#check whether any transaction id appears more than once
dup_row=df[df.duplicated(keep=False)]
total=dup_row["TransactionID"].sum()
print(total)

2020

In [ ]:
#find customers whose names appears more than once
df[df["Customer"].duplicated(keep=False)]

    TransactionID Customer     Product  Amount
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [ ]:
# remove completely duplicated tranactions from the dataset while keeping first occurance
df.drop_duplicates(keep="first")

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [ ]:
# remove the tranaction id keep first
df = df.drop_duplicates(
    subset=["TransactionID"],
    keep="first")
print(df)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [ ]:
# remove duplicate records based on customer and product, keeping first occurance
df = df.drop_duplicates(
    subset=["Customer","Product"],
    keep="first")
print(df)

   TransactionID Customer     Product  Amount
0           1001     Ravi      Laptop   55000
1           1002    Priya      Mobile   25000
2           1003     Arun      Tablet   30000
3           1004    Sneha  Headphones    5000
4           1005    Kiran       Mouse    1500
5           1006   Anjali    Keyboard    2500
6           1007   Vikram     Monitor   18000
7           1008    Meena      Laptop   55000
8           1009    Rahul      Mobile   22000

In [ ]:
df = df.drop_duplicates(
    subset=["TransactionID"],
    keep="first")
print(df)

   TransactionID Customer     Product  Amount
0           1001     Ravi      Laptop   55000
1           1002    Priya      Mobile   25000
2           1003     Arun      Tablet   30000
3           1004    Sneha  Headphones    5000
4           1005    Kiran       Mouse    1500
5           1006   Anjali    Keyboard    2500
6           1007   Vikram     Monitor   18000
7           1008    Meena      Laptop   55000
8           1009    Rahul      Mobile   22000

In [ ]:
#Dataset 2 – Hospital Patient Visits
#This dataset represents patient visit information in a hospital.
import pandas as pd
data = {

   "VisitID": [501, 502, 503, 504, 505,

               506, 507, 508, 509, 510, 510, 511],

   "Patient": ["Rahul", "Anita", "Suresh", "Priya", "Kiran",

               "Anjali", "Ravi", "Meena", "Arun", "Priya",

               "Priya", "Kiran"],

   "Department": ["Cardiology", "Neurology", "Orthopedic", "General",

                  "Dental", "Cardiology", "Neurology", "General",

                  "Dental", "Cardiology", "Cardiology", "Dental"],

   "BillAmount": [5000, 7500, 4500, 2000, 1500,

                  6000, 7000, 2500, 1800, 6000,6000, 1500]}


df = pd.DataFrame(data)

print(df)

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [ ]:
# count the number of duplicate patient visit records
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
dtype: bool

In [ ]:
#display all records involved in duplication first occurance
dup_row=df[df.duplicated(keep=False)]
print(dup_row)

    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000

In [ ]:
# calculate the total bill amount associated with the dulpicate records
dup_row=df[df.duplicated(keep=False)]
total=dup_row["BillAmount"].sum()
print(total)

12000

In [ ]:
# check whether any visitID has been entered more than once.display records with
# duplicate visit ID's
df[df["VisitID"].duplicated(keep=False)]

    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000

In [ ]:
#
df_patients = pd.DataFrame(data)
print(df_patients)

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [ ]:
#20/08/2026
#about groupby

In [ ]:
# Inconsistent data
#Inconsistent data means the data is not in a uniform or expected format, or the same type of information has different values/formats in different records.
#title()
#lover()
#upper()
#str

In [ ]:
df["Department"].str.title()

0     Cardiology
1      Neurology
2     Orthopedic
3        General
4         Dental
5     Cardiology
6      Neurology
7        General
8         Dental
9     Cardiology
10    Cardiology
11        Dental
Name: Department, dtype: object

In [ ]:
df["Patient"].str.strip()

0      Rahul
1      Anita
2     Suresh
3      Priya
4      Kiran
5     Anjali
6       Ravi
7      Meena
8       Arun
9      Priya
10     Priya
11     Kiran
Name: Patient, dtype: object

In [ ]:
# time series date 22-08-2026
import pandas as pd
data = {
    "Date":[
        "2025-01-01",
        "2025-01-02",
        "2025-01-03",
        "2025-01-04",
        "2025-01-05"
    ],
    "Sales":[5000,6500,4200,7000,5500]}
df = pd.DataFrame(data)
print(df)
print(df.dtypes)

         Date  Sales
0  2025-01-01   5000
1  2025-01-02   6500
2  2025-01-03   4200
3  2025-01-04   7000
4  2025-01-05   5500
Date     object
Sales     int64
dtype: object

In [ ]:
# changing to date time values
df["Date"] = pd.to_datetime(df["Date"])
print(df.dtypes)

Date     datetime64[ns]
Sales             int64
dtype: object

In [ ]:
#Synthetic time series
dates = pd.date_range(
    start="2025-01-01",
    end="2025-01-10"
)
print(dates)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
#generating a fixed number od dates
dates = pd.date_range(
    start="2025-01-01",
    periods=10
)
print(dates)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
#generating data with frequency for minutes
dates = pd.date_range(start="2025-01-01",periods=10,freq="min")
print(dates)

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 00:01:00',
               '2025-01-01 00:02:00', '2025-01-01 00:03:00',
               '2025-01-01 00:04:00', '2025-01-01 00:05:00',
               '2025-01-01 00:06:00', '2025-01-01 00:07:00',
               '2025-01-01 00:08:00', '2025-01-01 00:09:00'],
              dtype='datetime64[ns]', freq='min')

In [ ]:
#generating data with frequency for days
dates = pd.date_range(start="2025-01-01",periods=10,freq="D")
print(dates)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
#generating data with frequency for hours
dates = pd.date_range(start="2025-01-01",periods=10,freq="H")
print(dates)

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 01:00:00',
               '2025-01-01 02:00:00', '2025-01-01 03:00:00',
               '2025-01-01 04:00:00', '2025-01-01 05:00:00',
               '2025-01-01 06:00:00', '2025-01-01 07:00:00',
               '2025-01-01 08:00:00', '2025-01-01 09:00:00'],
              dtype='datetime64[ns]', freq='h')

/tmp/ipykernel_598/3607510579.py:2: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range(start="2025-01-01",periods=10,freq="H")

In [ ]:
#generating data with frequency for monthly
dates = pd.date_range(start="2025-01-01",periods=13,freq="ME")
print(dates)

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31',
               '2026-01-31'],
              dtype='datetime64[ns]', freq='ME')

In [ ]:
# creating Synthetic sales dataset
import pandas as pd
import numpy as np
dates = pd.date_range(start="2025-01-01",periods=30,freq="D")
sales = np.random.randint(2000,10000,size=30)
df = pd.DataFrame({
    "Dates":dates,
    "Sales":sales
})
print(df)

        Dates  Sales
0  2025-01-01   6858
1  2025-01-02   2245
2  2025-01-03   8642
3  2025-01-04   8623
4  2025-01-05   7911
5  2025-01-06   6526
6  2025-01-07   4590
7  2025-01-08   8401
8  2025-01-09   3757
9  2025-01-10   4359
10 2025-01-11   8596
11 2025-01-12   3683
12 2025-01-13   9451
13 2025-01-14   3419
14 2025-01-15   9315
15 2025-01-16   7653
16 2025-01-17   4686
17 2025-01-18   4641
18 2025-01-19   9640
19 2025-01-20   7309
20 2025-01-21   9396
21 2025-01-22   5383
22 2025-01-23   8298
23 2025-01-24   7893
24 2025-01-25   4707
25 2025-01-26   9955
26 2025-01-27   5706
27 2025-01-28   9184
28 2025-01-29   6873
29 2025-01-30   9308

In [ ]:
df["Dates"].dt.year

0     2025
1     2025
2     2025
3     2025
4     2025
5     2025
6     2025
7     2025
8     2025
9     2025
10    2025
11    2025
12    2025
13    2025
14    2025
15    2025
16    2025
17    2025
18    2025
19    2025
20    2025
21    2025
22    2025
23    2025
24    2025
25    2025
26    2025
27    2025
28    2025
29    2025
Name: Dates, dtype: int32

In [ ]:
df[df["Dates"].dt.year == 2025]

        Dates  Sales
0  2025-01-01   6858
1  2025-01-02   2245
2  2025-01-03   8642
3  2025-01-04   8623
4  2025-01-05   7911
5  2025-01-06   6526
6  2025-01-07   4590
7  2025-01-08   8401
8  2025-01-09   3757
9  2025-01-10   4359
10 2025-01-11   8596
11 2025-01-12   3683
12 2025-01-13   9451
13 2025-01-14   3419
14 2025-01-15   9315
15 2025-01-16   7653
16 2025-01-17   4686
17 2025-01-18   4641
18 2025-01-19   9640
19 2025-01-20   7309
20 2025-01-21   9396
21 2025-01-22   5383
22 2025-01-23   8298
23 2025-01-24   7893
24 2025-01-25   4707
25 2025-01-26   9955
26 2025-01-27   5706
27 2025-01-28   9184
28 2025-01-29   6873
29 2025-01-30   9308

In [ ]:
df["Year"]=df["Dates"].dt.year
print(df)

        Dates  Sales  Year
0  2025-01-01   6858  2025
1  2025-01-02   2245  2025
2  2025-01-03   8642  2025
3  2025-01-04   8623  2025
4  2025-01-05   7911  2025
5  2025-01-06   6526  2025
6  2025-01-07   4590  2025
7  2025-01-08   8401  2025
8  2025-01-09   3757  2025
9  2025-01-10   4359  2025
10 2025-01-11   8596  2025
11 2025-01-12   3683  2025
12 2025-01-13   9451  2025
13 2025-01-14   3419  2025
14 2025-01-15   9315  2025
15 2025-01-16   7653  2025
16 2025-01-17   4686  2025
17 2025-01-18   4641  2025
18 2025-01-19   9640  2025
19 2025-01-20   7309  2025
20 2025-01-21   9396  2025
21 2025-01-22   5383  2025
22 2025-01-23   8298  2025
23 2025-01-24   7893  2025
24 2025-01-25   4707  2025
25 2025-01-26   9955  2025
26 2025-01-27   5706  2025
27 2025-01-28   9184  2025
28 2025-01-29   6873  2025
29 2025-01-30   9308  2025

In [ ]:
df["Dates"].dt.month
df[df["Dates"].dt.month==1]

        Dates  Sales  Year
0  2025-01-01   6858  2025
1  2025-01-02   2245  2025
2  2025-01-03   8642  2025
3  2025-01-04   8623  2025
4  2025-01-05   7911  2025
5  2025-01-06   6526  2025
6  2025-01-07   4590  2025
7  2025-01-08   8401  2025
8  2025-01-09   3757  2025
9  2025-01-10   4359  2025
10 2025-01-11   8596  2025
11 2025-01-12   3683  2025
12 2025-01-13   9451  2025
13 2025-01-14   3419  2025
14 2025-01-15   9315  2025
15 2025-01-16   7653  2025
16 2025-01-17   4686  2025
17 2025-01-18   4641  2025
18 2025-01-19   9640  2025
19 2025-01-20   7309  2025
20 2025-01-21   9396  2025
21 2025-01-22   5383  2025
22 2025-01-23   8298  2025
23 2025-01-24   7893  2025
24 2025-01-25   4707  2025
25 2025-01-26   9955  2025
26 2025-01-27   5706  2025
27 2025-01-28   9184  2025
28 2025-01-29   6873  2025
29 2025-01-30   9308  2025

In [ ]:
# month name
df["Month"] = df["Dates"].dt.month_name()
print(df)

        Dates  Sales  Year    Month
0  2025-01-01   6858  2025  January
1  2025-01-02   2245  2025  January
2  2025-01-03   8642  2025  January
3  2025-01-04   8623  2025  January
4  2025-01-05   7911  2025  January
5  2025-01-06   6526  2025  January
6  2025-01-07   4590  2025  January
7  2025-01-08   8401  2025  January
8  2025-01-09   3757  2025  January
9  2025-01-10   4359  2025  January
10 2025-01-11   8596  2025  January
11 2025-01-12   3683  2025  January
12 2025-01-13   9451  2025  January
13 2025-01-14   3419  2025  January
14 2025-01-15   9315  2025  January
15 2025-01-16   7653  2025  January
16 2025-01-17   4686  2025  January
17 2025-01-18   4641  2025  January
18 2025-01-19   9640  2025  January
19 2025-01-20   7309  2025  January
20 2025-01-21   9396  2025  January
21 2025-01-22   5383  2025  January
22 2025-01-23   8298  2025  January
23 2025-01-24   7893  2025  January
24 2025-01-25   4707  2025  January
25 2025-01-26   9955  2025  January
26 2025-01-27   5706  2025  January
27 2025-01-28   9184  2025  January
28 2025-01-29   6873  2025  January
29 2025-01-30   9308  2025  January

In [ ]:
# filtering on day
df["Dates"].dt.day
df[df["Dates"].dt.day==14]

        Dates  Sales  Year    Month
13 2025-01-14   3419  2025  January

In [ ]:
# day of week
df["Dates"].dt.day_name()

0     Wednesday
1      Thursday
2        Friday
3      Saturday
4        Sunday
5        Monday
6       Tuesday
7     Wednesday
8      Thursday
9        Friday
10     Saturday
11       Sunday
12       Monday
13      Tuesday
14    Wednesday
15     Thursday
16       Friday
17     Saturday
18       Sunday
19       Monday
20      Tuesday
21    Wednesday
22     Thursday
23       Friday
24     Saturday
25       Sunday
26       Monday
27      Tuesday
28    Wednesday
29     Thursday
Name: Dates, dtype: object

In [ ]:
# for hours and seconds
df = pd.DataFrame ({
    "DateTime": pd.to_datetime([
        "2025-01-01 08:30:15",
        "2025-01-01 10:45:20",
        "2025-01-01 14:20:30",
        "2025-01-01 18:10:45"
    ]),
    "Sales":[2000,3500,5000,4200]
})
print(df)
df["DateTime"].dt.hour
df["DateTime"].dt.second

             DateTime  Sales
0 2025-01-01 08:30:15   2000
1 2025-01-01 10:45:20   3500
2 2025-01-01 14:20:30   5000
3 2025-01-01 18:10:45   4200

0    15
1    20
2    30
3    45
Name: DateTime, dtype: int32

In [ ]:
# Questions on numpy:-1
# 1.Create a numpy array containing numbers from 10to 50 with step of 5.Display the array.